version: "3.7"
services:
  database:
    container_name: postgres2
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: Reynald88
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data: